# Generated by Django 2.0.5 on 2018-12-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusomers',
            new_name='Customers',
        ),
    ]
