# Generated by Django 2.0.5 on 2018-12-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_auto_20181215_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='registerd_date',
            new_name='registered_date',
        ),
    ]
